import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TaskWithSubtasks, Task } from './services/task.service';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';

@Component({
  selector: 'app-task',
  standalone: true,
  imports: [CommonModule, MatCheckboxModule, MatIconModule, MatButtonModule],
  template: `
    <div class="p-6 border border-slate-200 rounded-3xl bg-white shadow-sm mb-4">
      <div class="flex justify-between items-center mb-4">
        <h3 class="text-xl font-bold text-slate-900">{{ task.maintask.title }}</h3>
        <button *ngIf="canDelete" mat-icon-button (click)="onDelete.emit(task)">
          <mat-icon>delete</mat-icon>
        </button>
      </div>
      <div class="space-y-2">
        <div *ngFor="let sub of task.subtasks" class="flex items-center gap-3">
          <mat-checkbox [checked]="sub.completed" (change)="toggleSubtask(sub)">
            <span [class.line-through]="sub.completed">{{ sub.title }}</span>
          </mat-checkbox>
        </div>
      </div>
      <div *ngIf="showGeneratedWithGemini" class="mt-4 text-[10px] text-indigo-500 font-bold uppercase tracking-widest">
        Generated by Gemini
      </div>
    </div>
  `
})
export class TaskComponent {
  @Input() task!: TaskWithSubtasks;
  @Input() canDelete = true;
  @Input() showGeneratedWithGemini = false;
  @Output() onDelete = new EventEmitter<TaskWithSubtasks>();
  @Output() onTasksCompletedToggle = new EventEmitter<Task[]>();

  toggleSubtask(sub: Task) {
    sub.completed = !sub.completed;
    this.onTasksCompletedToggle.emit([sub]);
  }
}
